baseURL = "https://brazil0nchain.com/"
title = "Brazil0nChain"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Brazil0nChain"
    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome to the brazuca smart contract hacking world!" 
    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Segurança em smart contracts, escrito com carinho para o brazuca médio!"
    # The name to display in the copyright section in the footer
    copyrightname = "demon-i386 / h4rry1337"
    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""
    # Show the "built on Hugo" disclaimer
    # Show the "built on Hugo" disclaimer
    showhugo = false
	
	# set theme to full screen width
	fullWidthTheme = true
 
    # Urls for social networks
    twitter = "https://x.com/brazil0nchain"
    telegram = "https://t.me/+7XwHY3E3FDAyZjMx"
    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false
    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 2.5
    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false
    
[params.copyright]
    name = "demon-i386 / h4rry1337 |"
    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""
    # Text to go before copyright information
    prefix = ""
    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""
[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "sobre" # An unique identifier for the button
    name = "Sobre"       # A display name for the button
    url = "/sobre/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20
[[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "/writeups/"       # The path can lead to a content folder too.
    weight = 20
[taxonomies]
category = "categories"
tag = "tags"
[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    # style = "api"
    tabWidth = 4

[imaging]
  resampleFilter = "lanczos"
  quality = 100
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.
