name: hugo

on:
  pull_request:
  push:

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Remove gh-pages branch
        run: |
          git fetch --prune --unshallow
          git branch -D gh-pages || true
          git push origin --delete gh-pages || true
      -
        name: Run Hugo
        uses: crazy-max/ghaction-hugo@v3
        with:
          version: latest
          extended: false
          args: --cleanDestinationDir --minify
      -
        name: Create CNAME file
        run: echo 'brazil0nchain.com' > public/CNAME
      -
        name: Deploy to GitHub Pages
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    deploy:
      permissions:
        contents: read
        pages: write
        id-token: write
      runs-on: ubuntu-latest
      needs: hugo
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Checkout gh-pages branch
          uses: actions/checkout@v2
          with:
            ref: gh-pages
            
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
          with:
            branch: gh-pages
            build_dir: public
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
